"""Konstanten aus Pre-Flight-Steps. NICHT manuell editieren.

Generated by preflight scripts. Values are filled in by the respective check scripts.
"""

# Set by preflight/check_exp09_schema.py (Step 0.1)
EXP09_TABLE = "results"
EXP09_COL_IMAGE = "image_path_aolp"
EXP09_COL_GT_COUNT = "strips_inside_box_count"
EXP09_COL_FRAME_ID = "measurement_frame"

# Set by preflight/extract_measurement_box.py (Step 0.2)
# Format: (y0, x0, y1, x1) in pixel coordinates; None until Step 0.2 runs.
MEASUREMENT_BOX = (0, 0, 512, 512)  # pixel (y0,x0,y1,x1); world center=(-6.0, 0.0, 0.1) dims=(15.0, 15.0, 0.2)

# Set by preflight/check_csrnet_layers.py (Step 0.4)
CSRNET_FEATURE_LAYER = "backend.4"
CSRNET_FEATURE_DIM = 512
